import 'dart:io';

import 'package:htmltopdfwidgets/htmltopdfwidgets.dart';
import 'package:test/test.dart';

late Document pdf;
late Document testPdf;

void main() {
  const htmlText = '''  <h1>Heading Example</h1>
  <p>This is a paragraph.</p>
  <img src="image.jpg" alt="Example Image" />
  <blockquote>This is a quote.</blockquote>
  <ul>
    <li>First item</li>
    <li>Second item</li>
    <li>Third item</li>
  </ul>
  <table>
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
</table>''';

  setUpAll(() {
    Document.debug = true;
    RichText.debug = true;
    pdf = Document();
    testPdf = Document();
  });

  test('convertion_test', () async {
    List<Widget> widgets = await HTMLToPdf().convert(htmlText);
    pdf.addPage(MultiPage(
        maxPages: 200,
        build: (context) {
          return widgets;
        }));
  });

  // Test comprehensive HTML features
  test('comprehensive_features_test', () async {
    const comprehensiveHtml = '''
      <h1 style="margin-bottom:20px">Heading 1 with spacing</h1>
      <h2 style="padding-bottom:15px">Heading 2 with padding</h2>
      <h3>Heading 3</h3>
      <h4>Heading 4</h4>
      <h5>Heading 5</h5>
      <h6>Heading 6</h6>
      
      <p style="margin-bottom:10px">Paragraph with spacing and <span style="font-size:16px;color:#FF0000">red colored text</span>.</p>
      <p>Another paragraph with <span style="font-size:20pt">larger font size in pt</span>.</p>
      <p>Text with <span style="font-size:18">numeric font size</span>.</p>
      
      <ul style="margin-bottom:20px">
        <li>First level item 1</li>
        <li>First level item 2
          <ul>
            <li>Second level item 1</li>
            <li>Second level item 2
              <ul>
                <li>Third level item</li>
              </ul>
            </li>
          </ul>
        </li>
        <li>First level item 3</li>
      </ul>
      
      <ol style="padding-bottom:15px">
        <li>Ordered item 1</li>
        <li>Ordered item 2
          <ol>
            <li>Nested ordered 1</li>
            <li>Nested ordered 2</li>
          </ol>
        </li>
        <li>Ordered item 3</li>
      </ol>
      
      <h2>Mixed Nested Lists</h2>
      <ul>
        <li>Bullet item
          <ol>
            <li>Nested numbered item 1</li>
            <li>Nested numbered item 2</li>
          </ol>
        </li>
      </ul>
    ''';

    List<Widget> widgets = await HTMLToPdf().convert(comprehensiveHtml);
    testPdf.addPage(MultiPage(
        maxPages: 200,
        build: (context) {
          return widgets;
        }));
  });

  // Test custom heading styles with fallback
  test('custom_heading_styles_test', () async {
    const headingHtml = '''
      <h1>Custom H1</h1>
      <h2>Custom H2</h2>
      <h3>Custom H3</h3>
      <h4>Custom H4</h4>
      <h5>Custom H5</h5>
      <h6>Custom H6</h6>
    ''';

    final customTagStyle = HtmlTagStyle(
      h1Style: TextStyle(color: PdfColors.blue),
      h2Style: TextStyle(color: PdfColors.green),
      headingStyle: TextStyle(color: PdfColors.red), // Fallback for h3-h6
    );

    List<Widget> widgets = await HTMLToPdf().convert(
      headingHtml,
      tagStyle: customTagStyle,
    );

    expect(widgets.isNotEmpty, true);
  });

  const String markDown = """
# Basic Markdown Demo
---
The Basic Markdown Demo shows the effect of the four Markdown extension sets
on formatting basic and extended Markdown tags.

## Overview

The Dart [markdown](https://pub.dev/packages/markdown) package parses Markdown
into HTML. The flutter_markdown package builds on this package using the
abstract syntax tree generated by the parser to make a tree of widgets instead
of HTML elements.

The markdown package supports the basic block and inline Markdown syntax
specified in the original Markdown implementation as well as a few Markdown
extensions. The markdown package uses extension sets to make extension
management easy. There are four pre-defined extension sets; none, Common Mark,
GitHub Flavored, and GitHub Web. The default extension set used by the
flutter_markdown package is GitHub Flavored.

The Basic Markdown Demo shows the effect each of the pre-defined extension sets
has on a test Markdown document with basic and extended Markdown tags. Use the
Extension Set dropdown menu to select an extension set and view the Markdown
widget's output.

## Comments

Since GitHub Flavored is the default extension set, it is the initial setting
for the formatted Markdown view in the demo.
""";

  test('markdown_convertion_test', () async {
    List<Widget> widgets = await HTMLToPdf().convertMarkdown(markDown);
    pdf.addPage(MultiPage(
        maxPages: 200,
        build: (context) {
          return widgets;
        }));
  });

  tearDownAll(() async {
    final file = File('example.pdf');
    await file.writeAsBytes(await pdf.save());
    final testFile = File('comprehensive_test.pdf');
    await testFile.writeAsBytes(await testPdf.save());
  });
}
