// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');
  FfiGenerator(
    headers: Headers(
      entryPoints: [packageRoot.resolve('src/native_pdf_engine.h')],
    ),
    functions: Functions.includeSet({
      'generate_pdf',
      'generate_pdf_from_url',
    }),
    output: Output(
      dartFile:
          packageRoot.resolve('lib/src/native_pdf_engine_bindings.g.dart'),
      preamble: '''
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by ffigen

// ignore_for_file: unused_field
''',
    ),
  ).generate();
}
