import 'dart:io';

import 'package:jnigen/jnigen.dart';

void main(List<String> args) async {
  final packageRoot = Platform.script.resolve('../');
  await generateJniBindings(
    Config(
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          path: packageRoot.resolve('lib/src/android/'),
          structure: OutputStructure.packageStructure,
        ),
      ),
      androidSdkConfig: AndroidSdkConfig(
        addGradleDeps: true,
        addGradleSources: true,
        androidExample: 'example/',
      ),
      sourcePath: [packageRoot.resolve('android/src/main/kotlin')],
      classes: [
        'android.webkit.WebView',
        'android.webkit.WebViewClient',
        'android.webkit.WebResourceRequest',
        'android.webkit.WebResourceError',
        'android.webkit.WebSettings',
        'android.print.PrintManager',
        'android.print.PrintDocumentAdapter',
        'android.print.PrintAttributes',
        'android.print.PageRange',
        'android.content.Context',
        'android.app.Activity',
        'android.view.View',
        'android.graphics.pdf.PdfDocument',
        'android.view.ViewGroup',
        'android.webkit.WebView',
        'android.webkit.WebViewClient',
        'java.io.File',
        'java.io.FileOutputStream',
        'android.graphics.Canvas',
        'android.graphics.Paint',
        'android.graphics.Picture',
        'java.lang.Runnable',
      ],
      preamble: '// Generated by jnigen. Do not edit.\n',
    ),
  );
}
