// Copyright (c) 2025, the Dart project authors.
// Generates minimal Objective-C bindings for iOS and macOS PDF generation.

import 'dart:io';

import 'package:ffigen/ffigen.dart';
import 'package:logging/logging.dart';

void main() {
  Logger.root.level = Level.SEVERE;

  // Get SDK paths dynamically
  final iosSdkPath = Process.runSync('xcrun', [
    '--sdk',
    'iphoneos',
    '--show-sdk-path',
  ]).stdout.toString().trim();
  final macosSdkPath = Process.runSync('xcrun', [
    '--sdk',
    'macosx',
    '--show-sdk-path',
  ]).stdout.toString().trim();

  print('iOS SDK: $iosSdkPath');
  print('macOS SDK: $macosSdkPath');

  print('Generating iOS bindings...');

  // iOS Configuration - use SDK WebKit header for full protocol support
  final iosConfig = FfiGenerator(
    headers: Headers(
      entryPoints: [
        Uri.file(
          '$iosSdkPath/System/Library/Frameworks/WebKit.framework/Headers/WebKit.h',
        ),
        Uri.file(
          '$iosSdkPath/System/Library/Frameworks/Foundation.framework/Headers/NSURLRequest.h',
        ),
      ],
      compilerOptions: ['-isysroot', iosSdkPath],
    ),
    objectiveC: ObjectiveC(
      interfaces: Interfaces.includeSet({
        'WKWebView',
        'WKWebViewConfiguration',
        'WKPDFConfiguration',
        'NSURLRequest',

        // UIKit classes transitively referenced by WKWebView
        'UIAction',
        'UIMenu',
        'UISymbolEffectCompletionContext',
        'UITableViewCell',
        'UICellConfigurationState',
        'UITableViewHeaderFooterView',
        'UIViewConfigurationState',
      }),
      protocols: Protocols.includeSet({'WKNavigationDelegate'}),
    ),
    output: Output(
      dartFile: Uri.file('lib/src/native_pdf_engine_ios_bindings.dart'),
      objectiveCFile: Uri.file('ios/Classes/native_pdf_engine.m'),
      preamble: '''
// Native PDF Engine - iOS WebKit bindings
// Generated by ffigen. Do not edit.
// ignore_for_file: type=lint
''',
    ),
  );
  iosConfig.generate(logger: Logger.root);
  print('Generated iOS bindings.');

  print('Generating macOS bindings...');

  // macOS Configuration - use SDK WebKit header for full protocol support
  final macosConfig = FfiGenerator(
    headers: Headers(
      entryPoints: [
        Uri.file(
          '$macosSdkPath/System/Library/Frameworks/WebKit.framework/Headers/WebKit.h',
        ),
        Uri.file(
          '$macosSdkPath/System/Library/Frameworks/Foundation.framework/Headers/NSURLRequest.h',
        ),
      ],
      compilerOptions: ['-isysroot', macosSdkPath],
    ),
    objectiveC: ObjectiveC(
      interfaces: Interfaces.includeSet({
        'WKWebView',
        'WKWebViewConfiguration',
        'WKPDFConfiguration',
        'NSURLRequest',
      }),
      protocols: Protocols.includeSet({'WKNavigationDelegate'}),
    ),
    output: Output(
      dartFile: Uri.file('lib/src/native_pdf_engine_macos_bindings.dart'),
      objectiveCFile: Uri.file('macos/Classes/native_pdf_engine.m'),
      preamble: '''
// Native PDF Engine - macOS WebKit bindings
// Generated by ffigen. Do not edit.
// ignore_for_file: type=lint
''',
    ),
  );
  macosConfig.generate(logger: Logger.root);
  print('Generated macOS bindings.');

  // Print file sizes
  final iosFile = File('lib/src/native_pdf_engine_ios_bindings.dart');
  final macosFile = File('lib/src/native_pdf_engine_macos_bindings.dart');
  if (iosFile.existsSync()) {
    print(
      'iOS bindings: ${(iosFile.lengthSync() / 1024).toStringAsFixed(1)} KB',
    );
  }
  if (macosFile.existsSync()) {
    print(
      'macOS bindings: ${(macosFile.lengthSync() / 1024).toStringAsFixed(1)} KB',
    );
  }
}
