// Copyright (c) 2025, the Dart project authors.
// Generates minimal Objective-C bindings for iOS and macOS PDF generation.

import 'dart:io';

import 'package:ffigen/ffigen.dart';
import 'package:logging/logging.dart';

void main() {
  Logger.root.level = Level.SEVERE;

  // Get SDK paths
  final iosSdkPath = Process.runSync('xcrun', [
    '--sdk',
    'iphoneos',
    '--show-sdk-path',
  ]).stdout.toString().trim();
  final macosSdkPath = Process.runSync('xcrun', [
    '--sdk',
    'macosx',
    '--show-sdk-path',
  ]).stdout.toString().trim();

  print('Generating iOS bindings...');

  // iOS Configuration - use custom header file for full framework context
  final iosConfig = FfiGenerator(
    headers: Headers(
      entryPoints: [Uri.file('tool/ios_headers.h')],
      compilerOptions: ['-isysroot', iosSdkPath],
    ),
    objectiveC: ObjectiveC(
      interfaces: Interfaces.includeSet({
        // Core WebKit classes for PDF generation
        'WKWebView',
        'WKWebViewConfiguration',
        'WKPDFConfiguration',
        'NSURLRequest',
        // UIKit classes transitively referenced by WKWebView
        'UIAction',
        'UIMenu',
        'UISymbolEffectCompletionContext',
        'UITableViewCell',
        'UICellConfigurationState',
        'UITableViewHeaderFooterView',
        'UIViewConfigurationState',
      }),
      protocols: Protocols.includeSet({'WKNavigationDelegate'}),
    ),
    output: Output(
      dartFile: Uri.file('lib/src/native_pdf_engine_ios_bindings.dart'),
      objectiveCFile: Uri.file('ios/Classes/native_pdf_engine.m'),
      preamble: '''
// Native PDF Engine - iOS WebKit bindings
// Generated by ffigen. Do not edit.
''',
    ),
  );
  iosConfig.generate(logger: Logger.root);
  print('Generated iOS bindings.');

  print('Generating macOS bindings...');

  // macOS Configuration - use custom header file for full framework context
  final macosConfig = FfiGenerator(
    headers: Headers(
      entryPoints: [Uri.file('tool/macos_headers.h')],
      compilerOptions: ['-isysroot', macosSdkPath],
    ),
    objectiveC: ObjectiveC(
      interfaces: Interfaces.includeSet({
        'WKWebView',
        'WKWebViewConfiguration',
        'WKPDFConfiguration',
        'NSURLRequest',
      }),
      protocols: Protocols.includeSet({'WKNavigationDelegate'}),
    ),
    output: Output(
      dartFile: Uri.file('lib/src/native_pdf_engine_macos_bindings.dart'),
      objectiveCFile: Uri.file('macos/Classes/native_pdf_engine.m'),
      preamble: '''
// Native PDF Engine - macOS WebKit bindings
// Generated by ffigen. Do not edit.
''',
    ),
  );
  macosConfig.generate(logger: Logger.root);
  print('Generated macOS bindings.');

  // Print file sizes
  final iosFile = File('lib/src/native_pdf_engine.dart');
  final macosFile = File('lib/src/native_pdf_engine.dart');
  if (iosFile.existsSync()) {
    print(
      'iOS bindings: ${(iosFile.lengthSync() / 1024).toStringAsFixed(1)} KB',
    );
  }
  if (macosFile.existsSync()) {
    print(
      'macOS bindings: ${(macosFile.lengthSync() / 1024).toStringAsFixed(1)} KB',
    );
  }
}
