// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'Canvas.dart' as canvas$_;

/// from: `android.graphics.Picture`
class Picture extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Picture> $type;

  @jni$_.internal
  Picture.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/graphics/Picture');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Picture?> nullableType = $Picture$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Picture> type = $Picture$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Picture() {
    return Picture.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_new$1 = _class.constructorId(
    r'(Landroid/graphics/Picture;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.graphics.Picture picture)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Picture.new$1(Picture? picture) {
    final _$picture = picture?.reference ?? jni$_.jNullReference;
    return Picture.fromReference(
      _new$1(
        _class.reference.pointer,
        _id_new$1 as jni$_.JMethodIDPtr,
        _$picture.pointer,
      ).reference,
    );
  }

  static final _id_beginRecording = _class.instanceMethodId(
    r'beginRecording',
    r'(II)Landroid/graphics/Canvas;',
  );

  static final _beginRecording =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              int,
            )
          >();

  /// from: `public android.graphics.Canvas beginRecording(int i, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  canvas$_.Canvas? beginRecording(int i, int i1) {
    return _beginRecording(
      reference.pointer,
      _id_beginRecording as jni$_.JMethodIDPtr,
      i,
      i1,
    ).object<canvas$_.Canvas?>(const canvas$_.$Canvas$NullableType$());
  }

  static final _id_draw = _class.instanceMethodId(
    r'draw',
    r'(Landroid/graphics/Canvas;)V',
  );

  static final _draw =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void draw(android.graphics.Canvas canvas)`
  void draw(canvas$_.Canvas? canvas) {
    final _$canvas = canvas?.reference ?? jni$_.jNullReference;
    _draw(
      reference.pointer,
      _id_draw as jni$_.JMethodIDPtr,
      _$canvas.pointer,
    ).check();
  }

  static final _id_endRecording = _class.instanceMethodId(
    r'endRecording',
    r'()V',
  );

  static final _endRecording =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void endRecording()`
  void endRecording() {
    _endRecording(
      reference.pointer,
      _id_endRecording as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_getHeight = _class.instanceMethodId(r'getHeight', r'()I');

  static final _getHeight =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getHeight()`
  int getHeight() {
    return _getHeight(
      reference.pointer,
      _id_getHeight as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getWidth = _class.instanceMethodId(r'getWidth', r'()I');

  static final _getWidth =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getWidth()`
  int getWidth() {
    return _getWidth(
      reference.pointer,
      _id_getWidth as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_requiresHardwareAcceleration = _class.instanceMethodId(
    r'requiresHardwareAcceleration',
    r'()Z',
  );

  static final _requiresHardwareAcceleration =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean requiresHardwareAcceleration()`
  bool requiresHardwareAcceleration() {
    return _requiresHardwareAcceleration(
      reference.pointer,
      _id_requiresHardwareAcceleration as jni$_.JMethodIDPtr,
    ).boolean;
  }
}

final class $Picture$NullableType$ extends jni$_.JType<Picture?> {
  @jni$_.internal
  const $Picture$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/graphics/Picture;';

  @jni$_.internal
  @core$_.override
  Picture? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Picture.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Picture?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Picture$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Picture$NullableType$) &&
        other is $Picture$NullableType$;
  }
}

final class $Picture$Type$ extends jni$_.JType<Picture> {
  @jni$_.internal
  const $Picture$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/graphics/Picture;';

  @jni$_.internal
  @core$_.override
  Picture fromReference(jni$_.JReference reference) =>
      Picture.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Picture?> get nullableType => const $Picture$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Picture$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Picture$Type$) && other is $Picture$Type$;
  }
}
