// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `android.webkit.WebResourceRequest`
class WebResourceRequest extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<WebResourceRequest> $type;

  @jni$_.internal
  WebResourceRequest.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/webkit/WebResourceRequest',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<WebResourceRequest?> nullableType =
      $WebResourceRequest$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<WebResourceRequest> type =
      $WebResourceRequest$Type$();
  static final _id_getMethod = _class.instanceMethodId(
    r'getMethod',
    r'()Ljava/lang/String;',
  );

  static final _getMethod =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract java.lang.String getMethod()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getMethod() {
    return _getMethod(
      reference.pointer,
      _id_getMethod as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getRequestHeaders = _class.instanceMethodId(
    r'getRequestHeaders',
    r'()Ljava/util/Map;',
  );

  static final _getRequestHeaders =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract java.util.Map<java.lang.String, java.lang.String> getRequestHeaders()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JMap<jni$_.JString?, jni$_.JString?>? getRequestHeaders() {
    return _getRequestHeaders(
      reference.pointer,
      _id_getRequestHeaders as jni$_.JMethodIDPtr,
    ).object<jni$_.JMap<jni$_.JString?, jni$_.JString?>?>(
      const jni$_.$JMap$NullableType$<jni$_.JString?, jni$_.JString?>(
        jni$_.$JString$NullableType$(),
        jni$_.$JString$NullableType$(),
      ),
    );
  }

  static final _id_getUrl = _class.instanceMethodId(
    r'getUrl',
    r'()Landroid/net/Uri;',
  );

  static final _getUrl =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract android.net.Uri getUrl()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getUrl() {
    return _getUrl(
      reference.pointer,
      _id_getUrl as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }

  static final _id_hasGesture = _class.instanceMethodId(r'hasGesture', r'()Z');

  static final _hasGesture =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract boolean hasGesture()`
  bool hasGesture() {
    return _hasGesture(
      reference.pointer,
      _id_hasGesture as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_isForMainFrame = _class.instanceMethodId(
    r'isForMainFrame',
    r'()Z',
  );

  static final _isForMainFrame =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract boolean isForMainFrame()`
  bool isForMainFrame() {
    return _isForMainFrame(
      reference.pointer,
      _id_isForMainFrame as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_isRedirect = _class.instanceMethodId(r'isRedirect', r'()Z');

  static final _isRedirect =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract boolean isRedirect()`
  bool isRedirect() {
    return _isRedirect(
      reference.pointer,
      _id_isRedirect as jni$_.JMethodIDPtr,
    ).boolean;
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $WebResourceRequest> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'getMethod()Ljava/lang/String;') {
        final $r = _$impls[$p]!.getMethod();
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.$JObject$Type$())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
      if ($d == r'getRequestHeaders()Ljava/util/Map;') {
        final $r = _$impls[$p]!.getRequestHeaders();
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.$JObject$Type$())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
      if ($d == r'getUrl()Landroid/net/Uri;') {
        final $r = _$impls[$p]!.getUrl();
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.$JObject$Type$())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
      if ($d == r'hasGesture()Z') {
        final $r = _$impls[$p]!.hasGesture();
        return jni$_.JBoolean($r).reference.toPointer();
      }
      if ($d == r'isForMainFrame()Z') {
        final $r = _$impls[$p]!.isForMainFrame();
        return jni$_.JBoolean($r).reference.toPointer();
      }
      if ($d == r'isRedirect()Z') {
        final $r = _$impls[$p]!.isRedirect();
        return jni$_.JBoolean($r).reference.toPointer();
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $WebResourceRequest $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'android.webkit.WebResourceRequest',
      $p,
      _$invokePointer,
      [],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory WebResourceRequest.implement($WebResourceRequest $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return WebResourceRequest.fromReference($i.implementReference());
  }
}

abstract base mixin class $WebResourceRequest {
  factory $WebResourceRequest({
    required jni$_.JString? Function() getMethod,
    required jni$_.JMap<jni$_.JString?, jni$_.JString?>? Function()
    getRequestHeaders,
    required jni$_.JObject? Function() getUrl,
    required bool Function() hasGesture,
    required bool Function() isForMainFrame,
    required bool Function() isRedirect,
  }) = _$WebResourceRequest;

  jni$_.JString? getMethod();
  jni$_.JMap<jni$_.JString?, jni$_.JString?>? getRequestHeaders();
  jni$_.JObject? getUrl();
  bool hasGesture();
  bool isForMainFrame();
  bool isRedirect();
}

final class _$WebResourceRequest with $WebResourceRequest {
  _$WebResourceRequest({
    required jni$_.JString? Function() getMethod,
    required jni$_.JMap<jni$_.JString?, jni$_.JString?>? Function()
    getRequestHeaders,
    required jni$_.JObject? Function() getUrl,
    required bool Function() hasGesture,
    required bool Function() isForMainFrame,
    required bool Function() isRedirect,
  }) : _getMethod = getMethod,
       _getRequestHeaders = getRequestHeaders,
       _getUrl = getUrl,
       _hasGesture = hasGesture,
       _isForMainFrame = isForMainFrame,
       _isRedirect = isRedirect;

  final jni$_.JString? Function() _getMethod;
  final jni$_.JMap<jni$_.JString?, jni$_.JString?>? Function()
  _getRequestHeaders;
  final jni$_.JObject? Function() _getUrl;
  final bool Function() _hasGesture;
  final bool Function() _isForMainFrame;
  final bool Function() _isRedirect;

  jni$_.JString? getMethod() {
    return _getMethod();
  }

  jni$_.JMap<jni$_.JString?, jni$_.JString?>? getRequestHeaders() {
    return _getRequestHeaders();
  }

  jni$_.JObject? getUrl() {
    return _getUrl();
  }

  bool hasGesture() {
    return _hasGesture();
  }

  bool isForMainFrame() {
    return _isForMainFrame();
  }

  bool isRedirect() {
    return _isRedirect();
  }
}

final class $WebResourceRequest$NullableType$
    extends jni$_.JType<WebResourceRequest?> {
  @jni$_.internal
  const $WebResourceRequest$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/webkit/WebResourceRequest;';

  @jni$_.internal
  @core$_.override
  WebResourceRequest? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : WebResourceRequest.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<WebResourceRequest?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($WebResourceRequest$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($WebResourceRequest$NullableType$) &&
        other is $WebResourceRequest$NullableType$;
  }
}

final class $WebResourceRequest$Type$ extends jni$_.JType<WebResourceRequest> {
  @jni$_.internal
  const $WebResourceRequest$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/webkit/WebResourceRequest;';

  @jni$_.internal
  @core$_.override
  WebResourceRequest fromReference(jni$_.JReference reference) =>
      WebResourceRequest.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<WebResourceRequest?> get nullableType =>
      const $WebResourceRequest$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($WebResourceRequest$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($WebResourceRequest$Type$) &&
        other is $WebResourceRequest$Type$;
  }
}
