// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../android/app/Activity.dart' as activity$_;

/// from: `com.example.native_pdf_engine.NativePdfEnginePlugin$Companion`
class NativePdfEnginePlugin$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<NativePdfEnginePlugin$Companion> $type;

  @jni$_.internal
  NativePdfEnginePlugin$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/native_pdf_engine/NativePdfEnginePlugin$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NativePdfEnginePlugin$Companion?> nullableType =
      $NativePdfEnginePlugin$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NativePdfEnginePlugin$Companion> type =
      $NativePdfEnginePlugin$Companion$Type$();
  static final _id_getActivity = _class.instanceMethodId(
    r'getActivity',
    r'()Landroid/app/Activity;',
  );

  static final _getActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final android.app.Activity getActivity()`
  /// The returned object must be released after use, by calling the [release] method.
  activity$_.Activity? getActivity() {
    return _getActivity(
      reference.pointer,
      _id_getActivity as jni$_.JMethodIDPtr,
    ).object<activity$_.Activity?>(const activity$_.$Activity$NullableType$());
  }

  static final _id_setActivity = _class.instanceMethodId(
    r'setActivity',
    r'(Landroid/app/Activity;)V',
  );

  static final _setActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setActivity(android.app.Activity activity)`
  void setActivity(activity$_.Activity? activity) {
    final _$activity = activity?.reference ?? jni$_.jNullReference;
    _setActivity(
      reference.pointer,
      _id_setActivity as jni$_.JMethodIDPtr,
      _$activity.pointer,
    ).check();
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory NativePdfEnginePlugin$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return NativePdfEnginePlugin$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $NativePdfEnginePlugin$Companion$NullableType$
    extends jni$_.JType<NativePdfEnginePlugin$Companion?> {
  @jni$_.internal
  const $NativePdfEnginePlugin$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/native_pdf_engine/NativePdfEnginePlugin$Companion;';

  @jni$_.internal
  @core$_.override
  NativePdfEnginePlugin$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : NativePdfEnginePlugin$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NativePdfEnginePlugin$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NativePdfEnginePlugin$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($NativePdfEnginePlugin$Companion$NullableType$) &&
        other is $NativePdfEnginePlugin$Companion$NullableType$;
  }
}

final class $NativePdfEnginePlugin$Companion$Type$
    extends jni$_.JType<NativePdfEnginePlugin$Companion> {
  @jni$_.internal
  const $NativePdfEnginePlugin$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/native_pdf_engine/NativePdfEnginePlugin$Companion;';

  @jni$_.internal
  @core$_.override
  NativePdfEnginePlugin$Companion fromReference(jni$_.JReference reference) =>
      NativePdfEnginePlugin$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NativePdfEnginePlugin$Companion?> get nullableType =>
      const $NativePdfEnginePlugin$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NativePdfEnginePlugin$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NativePdfEnginePlugin$Companion$Type$) &&
        other is $NativePdfEnginePlugin$Companion$Type$;
  }
}

/// from: `com.example.native_pdf_engine.NativePdfEnginePlugin`
class NativePdfEnginePlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<NativePdfEnginePlugin> $type;

  @jni$_.internal
  NativePdfEnginePlugin.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/native_pdf_engine/NativePdfEnginePlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NativePdfEnginePlugin?> nullableType =
      $NativePdfEnginePlugin$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<NativePdfEnginePlugin> type =
      $NativePdfEnginePlugin$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/example/native_pdf_engine/NativePdfEnginePlugin$Companion;',
  );

  /// from: `static public final com.example.native_pdf_engine.NativePdfEnginePlugin$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static NativePdfEnginePlugin$Companion get Companion =>
      _id_Companion.get(_class, const $NativePdfEnginePlugin$Companion$Type$());

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory NativePdfEnginePlugin() {
    return NativePdfEnginePlugin.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_onAttachedToEngine = _class.instanceMethodId(
    r'onAttachedToEngine',
    r'(Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;)V',
  );

  static final _onAttachedToEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onAttachedToEngine(flutterPluginBinding: io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding): kotlin.Unit`
  void onAttachedToEngine(jni$_.JObject flutterPluginBinding) {
    final _$flutterPluginBinding = flutterPluginBinding.reference;
    _onAttachedToEngine(
      reference.pointer,
      _id_onAttachedToEngine as jni$_.JMethodIDPtr,
      _$flutterPluginBinding.pointer,
    ).check();
  }

  static final _id_onMethodCall = _class.instanceMethodId(
    r'onMethodCall',
    r'(Lio/flutter/plugin/common/MethodCall;Lio/flutter/plugin/common/MethodChannel$Result;)V',
  );

  static final _onMethodCall =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onMethodCall(call: io.flutter.plugin.common.MethodCall, result: io.flutter.plugin.common.MethodChannel.Result): kotlin.Unit`
  void onMethodCall(jni$_.JObject methodCall, jni$_.JObject result) {
    final _$methodCall = methodCall.reference;
    final _$result = result.reference;
    _onMethodCall(
      reference.pointer,
      _id_onMethodCall as jni$_.JMethodIDPtr,
      _$methodCall.pointer,
      _$result.pointer,
    ).check();
  }

  static final _id_onDetachedFromEngine = _class.instanceMethodId(
    r'onDetachedFromEngine',
    r'(Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;)V',
  );

  static final _onDetachedFromEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onDetachedFromEngine(binding: io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding): kotlin.Unit`
  void onDetachedFromEngine(jni$_.JObject flutterPluginBinding) {
    final _$flutterPluginBinding = flutterPluginBinding.reference;
    _onDetachedFromEngine(
      reference.pointer,
      _id_onDetachedFromEngine as jni$_.JMethodIDPtr,
      _$flutterPluginBinding.pointer,
    ).check();
  }

  static final _id_onAttachedToActivity = _class.instanceMethodId(
    r'onAttachedToActivity',
    r'(Lio/flutter/embedding/engine/plugins/activity/ActivityPluginBinding;)V',
  );

  static final _onAttachedToActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onAttachedToActivity(binding: io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding): kotlin.Unit`
  void onAttachedToActivity(jni$_.JObject activityPluginBinding) {
    final _$activityPluginBinding = activityPluginBinding.reference;
    _onAttachedToActivity(
      reference.pointer,
      _id_onAttachedToActivity as jni$_.JMethodIDPtr,
      _$activityPluginBinding.pointer,
    ).check();
  }

  static final _id_onDetachedFromActivityForConfigChanges = _class
      .instanceMethodId(r'onDetachedFromActivityForConfigChanges', r'()V');

  static final _onDetachedFromActivityForConfigChanges =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun onDetachedFromActivityForConfigChanges(): kotlin.Unit`
  void onDetachedFromActivityForConfigChanges() {
    _onDetachedFromActivityForConfigChanges(
      reference.pointer,
      _id_onDetachedFromActivityForConfigChanges as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_onReattachedToActivityForConfigChanges = _class
      .instanceMethodId(
        r'onReattachedToActivityForConfigChanges',
        r'(Lio/flutter/embedding/engine/plugins/activity/ActivityPluginBinding;)V',
      );

  static final _onReattachedToActivityForConfigChanges =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onReattachedToActivityForConfigChanges(binding: io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding): kotlin.Unit`
  void onReattachedToActivityForConfigChanges(
    jni$_.JObject activityPluginBinding,
  ) {
    final _$activityPluginBinding = activityPluginBinding.reference;
    _onReattachedToActivityForConfigChanges(
      reference.pointer,
      _id_onReattachedToActivityForConfigChanges as jni$_.JMethodIDPtr,
      _$activityPluginBinding.pointer,
    ).check();
  }

  static final _id_onDetachedFromActivity = _class.instanceMethodId(
    r'onDetachedFromActivity',
    r'()V',
  );

  static final _onDetachedFromActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun onDetachedFromActivity(): kotlin.Unit`
  void onDetachedFromActivity() {
    _onDetachedFromActivity(
      reference.pointer,
      _id_onDetachedFromActivity as jni$_.JMethodIDPtr,
    ).check();
  }
}

final class $NativePdfEnginePlugin$NullableType$
    extends jni$_.JType<NativePdfEnginePlugin?> {
  @jni$_.internal
  const $NativePdfEnginePlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/native_pdf_engine/NativePdfEnginePlugin;';

  @jni$_.internal
  @core$_.override
  NativePdfEnginePlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : NativePdfEnginePlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NativePdfEnginePlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NativePdfEnginePlugin$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NativePdfEnginePlugin$NullableType$) &&
        other is $NativePdfEnginePlugin$NullableType$;
  }
}

final class $NativePdfEnginePlugin$Type$
    extends jni$_.JType<NativePdfEnginePlugin> {
  @jni$_.internal
  const $NativePdfEnginePlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/native_pdf_engine/NativePdfEnginePlugin;';

  @jni$_.internal
  @core$_.override
  NativePdfEnginePlugin fromReference(jni$_.JReference reference) =>
      NativePdfEnginePlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<NativePdfEnginePlugin?> get nullableType =>
      const $NativePdfEnginePlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($NativePdfEnginePlugin$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($NativePdfEnginePlugin$Type$) &&
        other is $NativePdfEnginePlugin$Type$;
  }
}
