// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../android/app/Activity.dart' as activity$_;

/// from: `com.example.native_pdf_engine.PdfGenerator$Callback`
class PdfGenerator$Callback extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PdfGenerator$Callback> $type;

  @jni$_.internal
  PdfGenerator$Callback.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/native_pdf_engine/PdfGenerator$Callback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfGenerator$Callback?> nullableType =
      $PdfGenerator$Callback$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfGenerator$Callback> type =
      $PdfGenerator$Callback$Type$();
  static final _id_onSuccess = _class.instanceMethodId(r'onSuccess', r'()V');

  static final _onSuccess =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun onSuccess(): kotlin.Unit`
  void onSuccess() {
    _onSuccess(reference.pointer, _id_onSuccess as jni$_.JMethodIDPtr).check();
  }

  static final _id_onFailure = _class.instanceMethodId(
    r'onFailure',
    r'(Ljava/lang/String;)V',
  );

  static final _onFailure =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onFailure(message: kotlin.String): kotlin.Unit`
  void onFailure(jni$_.JString string) {
    final _$string = string.reference;
    _onFailure(
      reference.pointer,
      _id_onFailure as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $PdfGenerator$Callback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onSuccess()V') {
        _$impls[$p]!.onSuccess();
        return jni$_.nullptr;
      }
      if ($d == r'onFailure(Ljava/lang/String;)V') {
        _$impls[$p]!.onFailure(
          $a![0]!.as(const jni$_.$JString$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $PdfGenerator$Callback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.example.native_pdf_engine.PdfGenerator$Callback',
      $p,
      _$invokePointer,
      [
        if ($impl.onSuccess$async) r'onSuccess()V',
        if ($impl.onFailure$async) r'onFailure(Ljava/lang/String;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory PdfGenerator$Callback.implement($PdfGenerator$Callback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return PdfGenerator$Callback.fromReference($i.implementReference());
  }
}

abstract base mixin class $PdfGenerator$Callback {
  factory $PdfGenerator$Callback({
    required void Function() onSuccess,
    bool onSuccess$async,
    required void Function(jni$_.JString string) onFailure,
    bool onFailure$async,
  }) = _$PdfGenerator$Callback;

  void onSuccess();
  bool get onSuccess$async => false;
  void onFailure(jni$_.JString string);
  bool get onFailure$async => false;
}

final class _$PdfGenerator$Callback with $PdfGenerator$Callback {
  _$PdfGenerator$Callback({
    required void Function() onSuccess,
    this.onSuccess$async = false,
    required void Function(jni$_.JString string) onFailure,
    this.onFailure$async = false,
  }) : _onSuccess = onSuccess,
       _onFailure = onFailure;

  final void Function() _onSuccess;
  final bool onSuccess$async;
  final void Function(jni$_.JString string) _onFailure;
  final bool onFailure$async;

  void onSuccess() {
    return _onSuccess();
  }

  void onFailure(jni$_.JString string) {
    return _onFailure(string);
  }
}

final class $PdfGenerator$Callback$NullableType$
    extends jni$_.JType<PdfGenerator$Callback?> {
  @jni$_.internal
  const $PdfGenerator$Callback$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/native_pdf_engine/PdfGenerator$Callback;';

  @jni$_.internal
  @core$_.override
  PdfGenerator$Callback? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : PdfGenerator$Callback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PdfGenerator$Callback?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PdfGenerator$Callback$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PdfGenerator$Callback$NullableType$) &&
        other is $PdfGenerator$Callback$NullableType$;
  }
}

final class $PdfGenerator$Callback$Type$
    extends jni$_.JType<PdfGenerator$Callback> {
  @jni$_.internal
  const $PdfGenerator$Callback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/native_pdf_engine/PdfGenerator$Callback;';

  @jni$_.internal
  @core$_.override
  PdfGenerator$Callback fromReference(jni$_.JReference reference) =>
      PdfGenerator$Callback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PdfGenerator$Callback?> get nullableType =>
      const $PdfGenerator$Callback$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PdfGenerator$Callback$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PdfGenerator$Callback$Type$) &&
        other is $PdfGenerator$Callback$Type$;
  }
}

/// from: `com.example.native_pdf_engine.PdfGenerator`
class PdfGenerator extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PdfGenerator> $type;

  @jni$_.internal
  PdfGenerator.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/native_pdf_engine/PdfGenerator',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfGenerator?> nullableType =
      $PdfGenerator$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PdfGenerator> type = $PdfGenerator$Type$();
  static final _id_new$ = _class.constructorId(r'(Landroid/app/Activity;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.app.Activity activity)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PdfGenerator(activity$_.Activity activity) {
    final _$activity = activity.reference;
    return PdfGenerator.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$activity.pointer,
      ).reference,
    );
  }

  static final _id_convert = _class.instanceMethodId(
    r'convert',
    r'(Ljava/lang/String;ZLjava/lang/String;Lcom/example/native_pdf_engine/PdfGenerator$Callback;)V',
  );

  static final _convert =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun convert(content: kotlin.String, isUrl: kotlin.Boolean, path: kotlin.String, callback: com.example.native_pdf_engine.PdfGenerator.Callback): kotlin.Unit`
  void convert(
    jni$_.JString string,
    bool z,
    jni$_.JString string1,
    PdfGenerator$Callback callback,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$callback = callback.reference;
    _convert(
      reference.pointer,
      _id_convert as jni$_.JMethodIDPtr,
      _$string.pointer,
      z ? 1 : 0,
      _$string1.pointer,
      _$callback.pointer,
    ).check();
  }
}

final class $PdfGenerator$NullableType$ extends jni$_.JType<PdfGenerator?> {
  @jni$_.internal
  const $PdfGenerator$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/native_pdf_engine/PdfGenerator;';

  @jni$_.internal
  @core$_.override
  PdfGenerator? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : PdfGenerator.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PdfGenerator?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PdfGenerator$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PdfGenerator$NullableType$) &&
        other is $PdfGenerator$NullableType$;
  }
}

final class $PdfGenerator$Type$ extends jni$_.JType<PdfGenerator> {
  @jni$_.internal
  const $PdfGenerator$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/native_pdf_engine/PdfGenerator;';

  @jni$_.internal
  @core$_.override
  PdfGenerator fromReference(jni$_.JReference reference) =>
      PdfGenerator.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PdfGenerator?> get nullableType =>
      const $PdfGenerator$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PdfGenerator$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PdfGenerator$Type$) &&
        other is $PdfGenerator$Type$;
  }
}
