// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'PrintAttributes.dart' as printattributes$_;

import 'PrintDocumentAdapter.dart' as printdocumentadapter$_;

/// from: `android.print.PrintManager`
class PrintManager extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintManager> $type;

  @jni$_.internal
  PrintManager.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/print/PrintManager');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintManager?> nullableType =
      $PrintManager$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintManager> type = $PrintManager$Type$();
  static final _id_getPrintJobs = _class.instanceMethodId(
    r'getPrintJobs',
    r'()Ljava/util/List;',
  );

  static final _getPrintJobs =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.List<android.print.PrintJob> getPrintJobs()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<jni$_.JObject?>? getPrintJobs() {
    return _getPrintJobs(
      reference.pointer,
      _id_getPrintJobs as jni$_.JMethodIDPtr,
    ).object<jni$_.JList<jni$_.JObject?>?>(
      const jni$_.$JList$NullableType$<jni$_.JObject?>(
        jni$_.$JObject$NullableType$(),
      ),
    );
  }

  static final _id_isPrintServiceEnabled = _class.instanceMethodId(
    r'isPrintServiceEnabled',
    r'(Landroid/content/ComponentName;)Z',
  );

  static final _isPrintServiceEnabled =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean isPrintServiceEnabled(android.content.ComponentName componentName)`
  bool isPrintServiceEnabled(jni$_.JObject? componentName) {
    final _$componentName = componentName?.reference ?? jni$_.jNullReference;
    return _isPrintServiceEnabled(
      reference.pointer,
      _id_isPrintServiceEnabled as jni$_.JMethodIDPtr,
      _$componentName.pointer,
    ).boolean;
  }

  static final _id_print = _class.instanceMethodId(
    r'print',
    r'(Ljava/lang/String;Landroid/print/PrintDocumentAdapter;Landroid/print/PrintAttributes;)Landroid/print/PrintJob;',
  );

  static final _print =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.print.PrintJob print(java.lang.String string, android.print.PrintDocumentAdapter printDocumentAdapter, android.print.PrintAttributes printAttributes)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? print(
    jni$_.JString? string,
    printdocumentadapter$_.PrintDocumentAdapter? printDocumentAdapter,
    printattributes$_.PrintAttributes? printAttributes,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$printDocumentAdapter =
        printDocumentAdapter?.reference ?? jni$_.jNullReference;
    final _$printAttributes =
        printAttributes?.reference ?? jni$_.jNullReference;
    return _print(
      reference.pointer,
      _id_print as jni$_.JMethodIDPtr,
      _$string.pointer,
      _$printDocumentAdapter.pointer,
      _$printAttributes.pointer,
    ).object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }
}

final class $PrintManager$NullableType$ extends jni$_.JType<PrintManager?> {
  @jni$_.internal
  const $PrintManager$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintManager;';

  @jni$_.internal
  @core$_.override
  PrintManager? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : PrintManager.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintManager?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintManager$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintManager$NullableType$) &&
        other is $PrintManager$NullableType$;
  }
}

final class $PrintManager$Type$ extends jni$_.JType<PrintManager> {
  @jni$_.internal
  const $PrintManager$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintManager;';

  @jni$_.internal
  @core$_.override
  PrintManager fromReference(jni$_.JReference reference) =>
      PrintManager.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintManager?> get nullableType =>
      const $PrintManager$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintManager$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintManager$Type$) &&
        other is $PrintManager$Type$;
  }
}
