// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'PageRange.dart' as pagerange$_;

import 'PrintAttributes.dart' as printattributes$_;

/// from: `android.print.PrintDocumentAdapter$LayoutResultCallback`
class PrintDocumentAdapter$LayoutResultCallback extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintDocumentAdapter$LayoutResultCallback> $type;

  @jni$_.internal
  PrintDocumentAdapter$LayoutResultCallback.fromReference(
    jni$_.JReference reference,
  ) : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/print/PrintDocumentAdapter$LayoutResultCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintDocumentAdapter$LayoutResultCallback?>
  nullableType = $PrintDocumentAdapter$LayoutResultCallback$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintDocumentAdapter$LayoutResultCallback> type =
      $PrintDocumentAdapter$LayoutResultCallback$Type$();
  static final _id_onLayoutCancelled = _class.instanceMethodId(
    r'onLayoutCancelled',
    r'()V',
  );

  static final _onLayoutCancelled =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void onLayoutCancelled()`
  void onLayoutCancelled() {
    _onLayoutCancelled(
      reference.pointer,
      _id_onLayoutCancelled as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_onLayoutFailed = _class.instanceMethodId(
    r'onLayoutFailed',
    r'(Ljava/lang/CharSequence;)V',
  );

  static final _onLayoutFailed =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onLayoutFailed(java.lang.CharSequence charSequence)`
  void onLayoutFailed(jni$_.JObject? charSequence) {
    final _$charSequence = charSequence?.reference ?? jni$_.jNullReference;
    _onLayoutFailed(
      reference.pointer,
      _id_onLayoutFailed as jni$_.JMethodIDPtr,
      _$charSequence.pointer,
    ).check();
  }

  static final _id_onLayoutFinished = _class.instanceMethodId(
    r'onLayoutFinished',
    r'(Landroid/print/PrintDocumentInfo;Z)V',
  );

  static final _onLayoutFinished =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public void onLayoutFinished(android.print.PrintDocumentInfo printDocumentInfo, boolean z)`
  void onLayoutFinished(jni$_.JObject? printDocumentInfo, bool z) {
    final _$printDocumentInfo =
        printDocumentInfo?.reference ?? jni$_.jNullReference;
    _onLayoutFinished(
      reference.pointer,
      _id_onLayoutFinished as jni$_.JMethodIDPtr,
      _$printDocumentInfo.pointer,
      z ? 1 : 0,
    ).check();
  }
}

final class $PrintDocumentAdapter$LayoutResultCallback$NullableType$
    extends jni$_.JType<PrintDocumentAdapter$LayoutResultCallback?> {
  @jni$_.internal
  const $PrintDocumentAdapter$LayoutResultCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Landroid/print/PrintDocumentAdapter$LayoutResultCallback;';

  @jni$_.internal
  @core$_.override
  PrintDocumentAdapter$LayoutResultCallback? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : PrintDocumentAdapter$LayoutResultCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintDocumentAdapter$LayoutResultCallback?> get nullableType =>
      this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($PrintDocumentAdapter$LayoutResultCallback$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($PrintDocumentAdapter$LayoutResultCallback$NullableType$) &&
        other is $PrintDocumentAdapter$LayoutResultCallback$NullableType$;
  }
}

final class $PrintDocumentAdapter$LayoutResultCallback$Type$
    extends jni$_.JType<PrintDocumentAdapter$LayoutResultCallback> {
  @jni$_.internal
  const $PrintDocumentAdapter$LayoutResultCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Landroid/print/PrintDocumentAdapter$LayoutResultCallback;';

  @jni$_.internal
  @core$_.override
  PrintDocumentAdapter$LayoutResultCallback fromReference(
    jni$_.JReference reference,
  ) => PrintDocumentAdapter$LayoutResultCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintDocumentAdapter$LayoutResultCallback?> get nullableType =>
      const $PrintDocumentAdapter$LayoutResultCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($PrintDocumentAdapter$LayoutResultCallback$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($PrintDocumentAdapter$LayoutResultCallback$Type$) &&
        other is $PrintDocumentAdapter$LayoutResultCallback$Type$;
  }
}

/// from: `android.print.PrintDocumentAdapter$WriteResultCallback`
class PrintDocumentAdapter$WriteResultCallback extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintDocumentAdapter$WriteResultCallback> $type;

  @jni$_.internal
  PrintDocumentAdapter$WriteResultCallback.fromReference(
    jni$_.JReference reference,
  ) : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/print/PrintDocumentAdapter$WriteResultCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintDocumentAdapter$WriteResultCallback?>
  nullableType = $PrintDocumentAdapter$WriteResultCallback$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintDocumentAdapter$WriteResultCallback> type =
      $PrintDocumentAdapter$WriteResultCallback$Type$();
  static final _id_onWriteCancelled = _class.instanceMethodId(
    r'onWriteCancelled',
    r'()V',
  );

  static final _onWriteCancelled =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void onWriteCancelled()`
  void onWriteCancelled() {
    _onWriteCancelled(
      reference.pointer,
      _id_onWriteCancelled as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_onWriteFailed = _class.instanceMethodId(
    r'onWriteFailed',
    r'(Ljava/lang/CharSequence;)V',
  );

  static final _onWriteFailed =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onWriteFailed(java.lang.CharSequence charSequence)`
  void onWriteFailed(jni$_.JObject? charSequence) {
    final _$charSequence = charSequence?.reference ?? jni$_.jNullReference;
    _onWriteFailed(
      reference.pointer,
      _id_onWriteFailed as jni$_.JMethodIDPtr,
      _$charSequence.pointer,
    ).check();
  }

  static final _id_onWriteFinished = _class.instanceMethodId(
    r'onWriteFinished',
    r'([Landroid/print/PageRange;)V',
  );

  static final _onWriteFinished =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onWriteFinished(android.print.PageRange[] pageRanges)`
  void onWriteFinished(jni$_.JArray<pagerange$_.PageRange?>? pageRanges) {
    final _$pageRanges = pageRanges?.reference ?? jni$_.jNullReference;
    _onWriteFinished(
      reference.pointer,
      _id_onWriteFinished as jni$_.JMethodIDPtr,
      _$pageRanges.pointer,
    ).check();
  }
}

final class $PrintDocumentAdapter$WriteResultCallback$NullableType$
    extends jni$_.JType<PrintDocumentAdapter$WriteResultCallback?> {
  @jni$_.internal
  const $PrintDocumentAdapter$WriteResultCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Landroid/print/PrintDocumentAdapter$WriteResultCallback;';

  @jni$_.internal
  @core$_.override
  PrintDocumentAdapter$WriteResultCallback? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : PrintDocumentAdapter$WriteResultCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintDocumentAdapter$WriteResultCallback?> get nullableType =>
      this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($PrintDocumentAdapter$WriteResultCallback$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($PrintDocumentAdapter$WriteResultCallback$NullableType$) &&
        other is $PrintDocumentAdapter$WriteResultCallback$NullableType$;
  }
}

final class $PrintDocumentAdapter$WriteResultCallback$Type$
    extends jni$_.JType<PrintDocumentAdapter$WriteResultCallback> {
  @jni$_.internal
  const $PrintDocumentAdapter$WriteResultCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Landroid/print/PrintDocumentAdapter$WriteResultCallback;';

  @jni$_.internal
  @core$_.override
  PrintDocumentAdapter$WriteResultCallback fromReference(
    jni$_.JReference reference,
  ) => PrintDocumentAdapter$WriteResultCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintDocumentAdapter$WriteResultCallback?> get nullableType =>
      const $PrintDocumentAdapter$WriteResultCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($PrintDocumentAdapter$WriteResultCallback$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($PrintDocumentAdapter$WriteResultCallback$Type$) &&
        other is $PrintDocumentAdapter$WriteResultCallback$Type$;
  }
}

/// from: `android.print.PrintDocumentAdapter`
class PrintDocumentAdapter extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintDocumentAdapter> $type;

  @jni$_.internal
  PrintDocumentAdapter.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/print/PrintDocumentAdapter',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintDocumentAdapter?> nullableType =
      $PrintDocumentAdapter$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintDocumentAdapter> type =
      $PrintDocumentAdapter$Type$();
  static final _id_EXTRA_PRINT_PREVIEW = _class.staticFieldId(
    r'EXTRA_PRINT_PREVIEW',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String EXTRA_PRINT_PREVIEW`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get EXTRA_PRINT_PREVIEW =>
      _id_EXTRA_PRINT_PREVIEW.get(_class, const jni$_.$JString$NullableType$());

  static final _id_onFinish = _class.instanceMethodId(r'onFinish', r'()V');

  static final _onFinish =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void onFinish()`
  void onFinish() {
    _onFinish(reference.pointer, _id_onFinish as jni$_.JMethodIDPtr).check();
  }

  static final _id_onLayout = _class.instanceMethodId(
    r'onLayout',
    r'(Landroid/print/PrintAttributes;Landroid/print/PrintAttributes;Landroid/os/CancellationSignal;Landroid/print/PrintDocumentAdapter$LayoutResultCallback;Landroid/os/Bundle;)V',
  );

  static final _onLayout =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void onLayout(android.print.PrintAttributes printAttributes, android.print.PrintAttributes printAttributes1, android.os.CancellationSignal cancellationSignal, android.print.PrintDocumentAdapter$LayoutResultCallback layoutResultCallback, android.os.Bundle bundle)`
  void onLayout(
    printattributes$_.PrintAttributes? printAttributes,
    printattributes$_.PrintAttributes? printAttributes1,
    jni$_.JObject? cancellationSignal,
    PrintDocumentAdapter$LayoutResultCallback? layoutResultCallback,
    jni$_.JObject? bundle,
  ) {
    final _$printAttributes =
        printAttributes?.reference ?? jni$_.jNullReference;
    final _$printAttributes1 =
        printAttributes1?.reference ?? jni$_.jNullReference;
    final _$cancellationSignal =
        cancellationSignal?.reference ?? jni$_.jNullReference;
    final _$layoutResultCallback =
        layoutResultCallback?.reference ?? jni$_.jNullReference;
    final _$bundle = bundle?.reference ?? jni$_.jNullReference;
    _onLayout(
      reference.pointer,
      _id_onLayout as jni$_.JMethodIDPtr,
      _$printAttributes.pointer,
      _$printAttributes1.pointer,
      _$cancellationSignal.pointer,
      _$layoutResultCallback.pointer,
      _$bundle.pointer,
    ).check();
  }

  static final _id_onStart = _class.instanceMethodId(r'onStart', r'()V');

  static final _onStart =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void onStart()`
  void onStart() {
    _onStart(reference.pointer, _id_onStart as jni$_.JMethodIDPtr).check();
  }

  static final _id_onWrite = _class.instanceMethodId(
    r'onWrite',
    r'([Landroid/print/PageRange;Landroid/os/ParcelFileDescriptor;Landroid/os/CancellationSignal;Landroid/print/PrintDocumentAdapter$WriteResultCallback;)V',
  );

  static final _onWrite =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void onWrite(android.print.PageRange[] pageRanges, android.os.ParcelFileDescriptor parcelFileDescriptor, android.os.CancellationSignal cancellationSignal, android.print.PrintDocumentAdapter$WriteResultCallback writeResultCallback)`
  void onWrite(
    jni$_.JArray<pagerange$_.PageRange?>? pageRanges,
    jni$_.JObject? parcelFileDescriptor,
    jni$_.JObject? cancellationSignal,
    PrintDocumentAdapter$WriteResultCallback? writeResultCallback,
  ) {
    final _$pageRanges = pageRanges?.reference ?? jni$_.jNullReference;
    final _$parcelFileDescriptor =
        parcelFileDescriptor?.reference ?? jni$_.jNullReference;
    final _$cancellationSignal =
        cancellationSignal?.reference ?? jni$_.jNullReference;
    final _$writeResultCallback =
        writeResultCallback?.reference ?? jni$_.jNullReference;
    _onWrite(
      reference.pointer,
      _id_onWrite as jni$_.JMethodIDPtr,
      _$pageRanges.pointer,
      _$parcelFileDescriptor.pointer,
      _$cancellationSignal.pointer,
      _$writeResultCallback.pointer,
    ).check();
  }
}

final class $PrintDocumentAdapter$NullableType$
    extends jni$_.JType<PrintDocumentAdapter?> {
  @jni$_.internal
  const $PrintDocumentAdapter$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintDocumentAdapter;';

  @jni$_.internal
  @core$_.override
  PrintDocumentAdapter? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : PrintDocumentAdapter.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintDocumentAdapter?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintDocumentAdapter$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintDocumentAdapter$NullableType$) &&
        other is $PrintDocumentAdapter$NullableType$;
  }
}

final class $PrintDocumentAdapter$Type$
    extends jni$_.JType<PrintDocumentAdapter> {
  @jni$_.internal
  const $PrintDocumentAdapter$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintDocumentAdapter;';

  @jni$_.internal
  @core$_.override
  PrintDocumentAdapter fromReference(jni$_.JReference reference) =>
      PrintDocumentAdapter.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintDocumentAdapter?> get nullableType =>
      const $PrintDocumentAdapter$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintDocumentAdapter$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintDocumentAdapter$Type$) &&
        other is $PrintDocumentAdapter$Type$;
  }
}
