// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `android.print.PrintAttributes$Builder`
class PrintAttributes$Builder extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintAttributes$Builder> $type;

  @jni$_.internal
  PrintAttributes$Builder.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/print/PrintAttributes$Builder',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Builder?> nullableType =
      $PrintAttributes$Builder$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Builder> type =
      $PrintAttributes$Builder$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory PrintAttributes$Builder() {
    return PrintAttributes$Builder.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_build = _class.instanceMethodId(
    r'build',
    r'()Landroid/print/PrintAttributes;',
  );

  static final _build =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes build()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes? build() {
    return _build(
      reference.pointer,
      _id_build as jni$_.JMethodIDPtr,
    ).object<PrintAttributes?>(const $PrintAttributes$NullableType$());
  }

  static final _id_setColorMode = _class.instanceMethodId(
    r'setColorMode',
    r'(I)Landroid/print/PrintAttributes$Builder;',
  );

  static final _setColorMode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setColorMode(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setColorMode(int i) {
    return _setColorMode(
      reference.pointer,
      _id_setColorMode as jni$_.JMethodIDPtr,
      i,
    ).object<PrintAttributes$Builder?>(
      const $PrintAttributes$Builder$NullableType$(),
    );
  }

  static final _id_setDuplexMode = _class.instanceMethodId(
    r'setDuplexMode',
    r'(I)Landroid/print/PrintAttributes$Builder;',
  );

  static final _setDuplexMode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setDuplexMode(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setDuplexMode(int i) {
    return _setDuplexMode(
      reference.pointer,
      _id_setDuplexMode as jni$_.JMethodIDPtr,
      i,
    ).object<PrintAttributes$Builder?>(
      const $PrintAttributes$Builder$NullableType$(),
    );
  }

  static final _id_setMediaSize = _class.instanceMethodId(
    r'setMediaSize',
    r'(Landroid/print/PrintAttributes$MediaSize;)Landroid/print/PrintAttributes$Builder;',
  );

  static final _setMediaSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setMediaSize(android.print.PrintAttributes$MediaSize mediaSize)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setMediaSize(PrintAttributes$MediaSize? mediaSize) {
    final _$mediaSize = mediaSize?.reference ?? jni$_.jNullReference;
    return _setMediaSize(
      reference.pointer,
      _id_setMediaSize as jni$_.JMethodIDPtr,
      _$mediaSize.pointer,
    ).object<PrintAttributes$Builder?>(
      const $PrintAttributes$Builder$NullableType$(),
    );
  }

  static final _id_setMinMargins = _class.instanceMethodId(
    r'setMinMargins',
    r'(Landroid/print/PrintAttributes$Margins;)Landroid/print/PrintAttributes$Builder;',
  );

  static final _setMinMargins =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setMinMargins(android.print.PrintAttributes$Margins margins)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setMinMargins(PrintAttributes$Margins? margins) {
    final _$margins = margins?.reference ?? jni$_.jNullReference;
    return _setMinMargins(
      reference.pointer,
      _id_setMinMargins as jni$_.JMethodIDPtr,
      _$margins.pointer,
    ).object<PrintAttributes$Builder?>(
      const $PrintAttributes$Builder$NullableType$(),
    );
  }

  static final _id_setResolution = _class.instanceMethodId(
    r'setResolution',
    r'(Landroid/print/PrintAttributes$Resolution;)Landroid/print/PrintAttributes$Builder;',
  );

  static final _setResolution =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.print.PrintAttributes$Builder setResolution(android.print.PrintAttributes$Resolution resolution)`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Builder? setResolution(
    PrintAttributes$Resolution? resolution,
  ) {
    final _$resolution = resolution?.reference ?? jni$_.jNullReference;
    return _setResolution(
      reference.pointer,
      _id_setResolution as jni$_.JMethodIDPtr,
      _$resolution.pointer,
    ).object<PrintAttributes$Builder?>(
      const $PrintAttributes$Builder$NullableType$(),
    );
  }
}

final class $PrintAttributes$Builder$NullableType$
    extends jni$_.JType<PrintAttributes$Builder?> {
  @jni$_.internal
  const $PrintAttributes$Builder$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Builder;';

  @jni$_.internal
  @core$_.override
  PrintAttributes$Builder? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : PrintAttributes$Builder.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes$Builder?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$Builder$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$Builder$NullableType$) &&
        other is $PrintAttributes$Builder$NullableType$;
  }
}

final class $PrintAttributes$Builder$Type$
    extends jni$_.JType<PrintAttributes$Builder> {
  @jni$_.internal
  const $PrintAttributes$Builder$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Builder;';

  @jni$_.internal
  @core$_.override
  PrintAttributes$Builder fromReference(jni$_.JReference reference) =>
      PrintAttributes$Builder.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes$Builder?> get nullableType =>
      const $PrintAttributes$Builder$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$Builder$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$Builder$Type$) &&
        other is $PrintAttributes$Builder$Type$;
  }
}

/// from: `android.print.PrintAttributes$Margins`
class PrintAttributes$Margins extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintAttributes$Margins> $type;

  @jni$_.internal
  PrintAttributes$Margins.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/print/PrintAttributes$Margins',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Margins?> nullableType =
      $PrintAttributes$Margins$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Margins> type =
      $PrintAttributes$Margins$Type$();
  static final _id_NO_MARGINS = _class.staticFieldId(
    r'NO_MARGINS',
    r'Landroid/print/PrintAttributes$Margins;',
  );

  /// from: `static public final android.print.PrintAttributes$Margins NO_MARGINS`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$Margins? get NO_MARGINS => _id_NO_MARGINS.get(
    _class,
    const $PrintAttributes$Margins$NullableType$(),
  );

  static final _id_new$ = _class.constructorId(r'(IIII)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Int32, jni$_.Int32, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              int,
              int,
              int,
            )
          >();

  /// from: `public void <init>(int i, int i1, int i2, int i3)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PrintAttributes$Margins(int i, int i1, int i2, int i3) {
    return PrintAttributes$Margins.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        i,
        i1,
        i2,
        i3,
      ).reference,
    );
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }

  static final _id_getBottomMils = _class.instanceMethodId(
    r'getBottomMils',
    r'()I',
  );

  static final _getBottomMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getBottomMils()`
  int getBottomMils() {
    return _getBottomMils(
      reference.pointer,
      _id_getBottomMils as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getLeftMils = _class.instanceMethodId(
    r'getLeftMils',
    r'()I',
  );

  static final _getLeftMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getLeftMils()`
  int getLeftMils() {
    return _getLeftMils(
      reference.pointer,
      _id_getLeftMils as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getRightMils = _class.instanceMethodId(
    r'getRightMils',
    r'()I',
  );

  static final _getRightMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getRightMils()`
  int getRightMils() {
    return _getRightMils(
      reference.pointer,
      _id_getRightMils as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getTopMils = _class.instanceMethodId(r'getTopMils', r'()I');

  static final _getTopMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getTopMils()`
  int getTopMils() {
    return _getTopMils(
      reference.pointer,
      _id_getTopMils as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_hashCode$1 = _class.instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  int hashCode$1() {
    return _hashCode$1(
      reference.pointer,
      _id_hashCode$1 as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }
}

final class $PrintAttributes$Margins$NullableType$
    extends jni$_.JType<PrintAttributes$Margins?> {
  @jni$_.internal
  const $PrintAttributes$Margins$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Margins;';

  @jni$_.internal
  @core$_.override
  PrintAttributes$Margins? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : PrintAttributes$Margins.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes$Margins?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$Margins$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$Margins$NullableType$) &&
        other is $PrintAttributes$Margins$NullableType$;
  }
}

final class $PrintAttributes$Margins$Type$
    extends jni$_.JType<PrintAttributes$Margins> {
  @jni$_.internal
  const $PrintAttributes$Margins$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Margins;';

  @jni$_.internal
  @core$_.override
  PrintAttributes$Margins fromReference(jni$_.JReference reference) =>
      PrintAttributes$Margins.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes$Margins?> get nullableType =>
      const $PrintAttributes$Margins$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$Margins$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$Margins$Type$) &&
        other is $PrintAttributes$Margins$Type$;
  }
}

/// from: `android.print.PrintAttributes$MediaSize`
class PrintAttributes$MediaSize extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintAttributes$MediaSize> $type;

  @jni$_.internal
  PrintAttributes$MediaSize.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/print/PrintAttributes$MediaSize',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$MediaSize?> nullableType =
      $PrintAttributes$MediaSize$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$MediaSize> type =
      $PrintAttributes$MediaSize$Type$();
  static final _id_ANSI_C = _class.staticFieldId(
    r'ANSI_C',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ANSI_C`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ANSI_C =>
      _id_ANSI_C.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ANSI_D = _class.staticFieldId(
    r'ANSI_D',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ANSI_D`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ANSI_D =>
      _id_ANSI_D.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ANSI_E = _class.staticFieldId(
    r'ANSI_E',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ANSI_E`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ANSI_E =>
      _id_ANSI_E.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ANSI_F = _class.staticFieldId(
    r'ANSI_F',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ANSI_F`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ANSI_F =>
      _id_ANSI_F.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A0 = _class.staticFieldId(
    r'ISO_A0',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A0`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A0 =>
      _id_ISO_A0.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A1 = _class.staticFieldId(
    r'ISO_A1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A1 =>
      _id_ISO_A1.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A10 = _class.staticFieldId(
    r'ISO_A10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A10 =>
      _id_ISO_A10.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A2 = _class.staticFieldId(
    r'ISO_A2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A2 =>
      _id_ISO_A2.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A3 = _class.staticFieldId(
    r'ISO_A3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A3 =>
      _id_ISO_A3.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A4 = _class.staticFieldId(
    r'ISO_A4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A4 =>
      _id_ISO_A4.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A5 = _class.staticFieldId(
    r'ISO_A5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A5 =>
      _id_ISO_A5.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A6 = _class.staticFieldId(
    r'ISO_A6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A6 =>
      _id_ISO_A6.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A7 = _class.staticFieldId(
    r'ISO_A7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A7 =>
      _id_ISO_A7.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A8 = _class.staticFieldId(
    r'ISO_A8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A8 =>
      _id_ISO_A8.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_A9 = _class.staticFieldId(
    r'ISO_A9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_A9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_A9 =>
      _id_ISO_A9.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B0 = _class.staticFieldId(
    r'ISO_B0',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B0`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B0 =>
      _id_ISO_B0.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B1 = _class.staticFieldId(
    r'ISO_B1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B1 =>
      _id_ISO_B1.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B10 = _class.staticFieldId(
    r'ISO_B10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B10 =>
      _id_ISO_B10.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B2 = _class.staticFieldId(
    r'ISO_B2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B2 =>
      _id_ISO_B2.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B3 = _class.staticFieldId(
    r'ISO_B3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B3 =>
      _id_ISO_B3.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B4 = _class.staticFieldId(
    r'ISO_B4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B4 =>
      _id_ISO_B4.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B5 = _class.staticFieldId(
    r'ISO_B5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B5 =>
      _id_ISO_B5.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B6 = _class.staticFieldId(
    r'ISO_B6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B6 =>
      _id_ISO_B6.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B7 = _class.staticFieldId(
    r'ISO_B7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B7 =>
      _id_ISO_B7.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B8 = _class.staticFieldId(
    r'ISO_B8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B8 =>
      _id_ISO_B8.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_B9 = _class.staticFieldId(
    r'ISO_B9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_B9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_B9 =>
      _id_ISO_B9.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C0 = _class.staticFieldId(
    r'ISO_C0',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C0`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C0 =>
      _id_ISO_C0.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C1 = _class.staticFieldId(
    r'ISO_C1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C1 =>
      _id_ISO_C1.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C10 = _class.staticFieldId(
    r'ISO_C10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C10 =>
      _id_ISO_C10.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C2 = _class.staticFieldId(
    r'ISO_C2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C2 =>
      _id_ISO_C2.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C3 = _class.staticFieldId(
    r'ISO_C3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C3 =>
      _id_ISO_C3.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C4 = _class.staticFieldId(
    r'ISO_C4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C4 =>
      _id_ISO_C4.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C5 = _class.staticFieldId(
    r'ISO_C5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C5 =>
      _id_ISO_C5.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C6 = _class.staticFieldId(
    r'ISO_C6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C6 =>
      _id_ISO_C6.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C7 = _class.staticFieldId(
    r'ISO_C7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C7 =>
      _id_ISO_C7.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C8 = _class.staticFieldId(
    r'ISO_C8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C8 =>
      _id_ISO_C8.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ISO_C9 = _class.staticFieldId(
    r'ISO_C9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ISO_C9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ISO_C9 =>
      _id_ISO_C9.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B0 = _class.staticFieldId(
    r'JIS_B0',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B0`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B0 =>
      _id_JIS_B0.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B1 = _class.staticFieldId(
    r'JIS_B1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B1 =>
      _id_JIS_B1.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B10 = _class.staticFieldId(
    r'JIS_B10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B10 =>
      _id_JIS_B10.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B2 = _class.staticFieldId(
    r'JIS_B2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B2 =>
      _id_JIS_B2.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B3 = _class.staticFieldId(
    r'JIS_B3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B3 =>
      _id_JIS_B3.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B4 = _class.staticFieldId(
    r'JIS_B4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B4 =>
      _id_JIS_B4.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B5 = _class.staticFieldId(
    r'JIS_B5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B5 =>
      _id_JIS_B5.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B6 = _class.staticFieldId(
    r'JIS_B6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B6 =>
      _id_JIS_B6.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B7 = _class.staticFieldId(
    r'JIS_B7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B7 =>
      _id_JIS_B7.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B8 = _class.staticFieldId(
    r'JIS_B8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B8 =>
      _id_JIS_B8.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_B9 = _class.staticFieldId(
    r'JIS_B9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_B9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_B9 =>
      _id_JIS_B9.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JIS_EXEC = _class.staticFieldId(
    r'JIS_EXEC',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JIS_EXEC`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JIS_EXEC => _id_JIS_EXEC.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_JPN_CHOU2 = _class.staticFieldId(
    r'JPN_CHOU2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_CHOU2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_CHOU2 => _id_JPN_CHOU2.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_JPN_CHOU3 = _class.staticFieldId(
    r'JPN_CHOU3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_CHOU3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_CHOU3 => _id_JPN_CHOU3.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_JPN_CHOU4 = _class.staticFieldId(
    r'JPN_CHOU4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_CHOU4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_CHOU4 => _id_JPN_CHOU4.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_JPN_HAGAKI = _class.staticFieldId(
    r'JPN_HAGAKI',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_HAGAKI`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_HAGAKI => _id_JPN_HAGAKI.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_JPN_KAHU = _class.staticFieldId(
    r'JPN_KAHU',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_KAHU`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_KAHU => _id_JPN_KAHU.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_JPN_KAKU2 = _class.staticFieldId(
    r'JPN_KAKU2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_KAKU2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_KAKU2 => _id_JPN_KAKU2.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_JPN_OE_PHOTO_L = _class.staticFieldId(
    r'JPN_OE_PHOTO_L',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_OE_PHOTO_L`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_OE_PHOTO_L => _id_JPN_OE_PHOTO_L
      .get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_JPN_OUFUKU = _class.staticFieldId(
    r'JPN_OUFUKU',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_OUFUKU`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_OUFUKU => _id_JPN_OUFUKU.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_JPN_YOU4 = _class.staticFieldId(
    r'JPN_YOU4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize JPN_YOU4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get JPN_YOU4 => _id_JPN_YOU4.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_ARCH_A = _class.staticFieldId(
    r'NA_ARCH_A',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_A`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_A => _id_NA_ARCH_A.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_ARCH_B = _class.staticFieldId(
    r'NA_ARCH_B',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_B`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_B => _id_NA_ARCH_B.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_ARCH_C = _class.staticFieldId(
    r'NA_ARCH_C',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_C`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_C => _id_NA_ARCH_C.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_ARCH_D = _class.staticFieldId(
    r'NA_ARCH_D',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_D`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_D => _id_NA_ARCH_D.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_ARCH_E = _class.staticFieldId(
    r'NA_ARCH_E',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_E`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_E => _id_NA_ARCH_E.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_ARCH_E1 = _class.staticFieldId(
    r'NA_ARCH_E1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_ARCH_E1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_ARCH_E1 => _id_NA_ARCH_E1.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_FOOLSCAP = _class.staticFieldId(
    r'NA_FOOLSCAP',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_FOOLSCAP`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_FOOLSCAP => _id_NA_FOOLSCAP.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_GOVT_LETTER = _class.staticFieldId(
    r'NA_GOVT_LETTER',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_GOVT_LETTER`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_GOVT_LETTER => _id_NA_GOVT_LETTER
      .get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_NA_INDEX_3X5 = _class.staticFieldId(
    r'NA_INDEX_3X5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_INDEX_3X5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_INDEX_3X5 => _id_NA_INDEX_3X5.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_INDEX_4X6 = _class.staticFieldId(
    r'NA_INDEX_4X6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_INDEX_4X6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_INDEX_4X6 => _id_NA_INDEX_4X6.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_INDEX_5X8 = _class.staticFieldId(
    r'NA_INDEX_5X8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_INDEX_5X8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_INDEX_5X8 => _id_NA_INDEX_5X8.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_JUNIOR_LEGAL = _class.staticFieldId(
    r'NA_JUNIOR_LEGAL',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_JUNIOR_LEGAL`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_JUNIOR_LEGAL => _id_NA_JUNIOR_LEGAL
      .get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_NA_LEDGER = _class.staticFieldId(
    r'NA_LEDGER',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_LEDGER`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_LEDGER => _id_NA_LEDGER.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_LEGAL = _class.staticFieldId(
    r'NA_LEGAL',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_LEGAL`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_LEGAL => _id_NA_LEGAL.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_LETTER = _class.staticFieldId(
    r'NA_LETTER',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_LETTER`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_LETTER => _id_NA_LETTER.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_MONARCH = _class.staticFieldId(
    r'NA_MONARCH',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_MONARCH`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_MONARCH => _id_NA_MONARCH.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_QUARTO = _class.staticFieldId(
    r'NA_QUARTO',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_QUARTO`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_QUARTO => _id_NA_QUARTO.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_SUPER_B = _class.staticFieldId(
    r'NA_SUPER_B',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_SUPER_B`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_SUPER_B => _id_NA_SUPER_B.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_NA_TABLOID = _class.staticFieldId(
    r'NA_TABLOID',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize NA_TABLOID`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get NA_TABLOID => _id_NA_TABLOID.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_OM_DAI_PA_KAI = _class.staticFieldId(
    r'OM_DAI_PA_KAI',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize OM_DAI_PA_KAI`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get OM_DAI_PA_KAI => _id_OM_DAI_PA_KAI.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_OM_JUURO_KU_KAI = _class.staticFieldId(
    r'OM_JUURO_KU_KAI',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize OM_JUURO_KU_KAI`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get OM_JUURO_KU_KAI => _id_OM_JUURO_KU_KAI
      .get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_OM_PA_KAI = _class.staticFieldId(
    r'OM_PA_KAI',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize OM_PA_KAI`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get OM_PA_KAI => _id_OM_PA_KAI.get(
    _class,
    const $PrintAttributes$MediaSize$NullableType$(),
  );

  static final _id_PRC_1 = _class.staticFieldId(
    r'PRC_1',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_1`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_1 =>
      _id_PRC_1.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_10 = _class.staticFieldId(
    r'PRC_10',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_10`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_10 =>
      _id_PRC_10.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_16K = _class.staticFieldId(
    r'PRC_16K',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_16K`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_16K =>
      _id_PRC_16K.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_2 = _class.staticFieldId(
    r'PRC_2',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_2`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_2 =>
      _id_PRC_2.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_3 = _class.staticFieldId(
    r'PRC_3',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_3`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_3 =>
      _id_PRC_3.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_4 = _class.staticFieldId(
    r'PRC_4',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_4`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_4 =>
      _id_PRC_4.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_5 = _class.staticFieldId(
    r'PRC_5',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_5`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_5 =>
      _id_PRC_5.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_6 = _class.staticFieldId(
    r'PRC_6',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_6`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_6 =>
      _id_PRC_6.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_7 = _class.staticFieldId(
    r'PRC_7',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_7`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_7 =>
      _id_PRC_7.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_8 = _class.staticFieldId(
    r'PRC_8',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_8`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_8 =>
      _id_PRC_8.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_PRC_9 = _class.staticFieldId(
    r'PRC_9',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize PRC_9`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get PRC_9 =>
      _id_PRC_9.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ROC_16K = _class.staticFieldId(
    r'ROC_16K',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ROC_16K`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ROC_16K =>
      _id_ROC_16K.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_ROC_8K = _class.staticFieldId(
    r'ROC_8K',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize ROC_8K`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get ROC_8K =>
      _id_ROC_8K.get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_UNKNOWN_LANDSCAPE = _class.staticFieldId(
    r'UNKNOWN_LANDSCAPE',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize UNKNOWN_LANDSCAPE`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get UNKNOWN_LANDSCAPE =>
      _id_UNKNOWN_LANDSCAPE.get(
        _class,
        const $PrintAttributes$MediaSize$NullableType$(),
      );

  static final _id_UNKNOWN_PORTRAIT = _class.staticFieldId(
    r'UNKNOWN_PORTRAIT',
    r'Landroid/print/PrintAttributes$MediaSize;',
  );

  /// from: `static public final android.print.PrintAttributes$MediaSize UNKNOWN_PORTRAIT`
  /// The returned object must be released after use, by calling the [release] method.
  static PrintAttributes$MediaSize? get UNKNOWN_PORTRAIT => _id_UNKNOWN_PORTRAIT
      .get(_class, const $PrintAttributes$MediaSize$NullableType$());

  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;II)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1, int i, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PrintAttributes$MediaSize(
    jni$_.JString? string,
    jni$_.JString? string1,
    int i,
    int i1,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    return PrintAttributes$MediaSize.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$string.pointer,
        _$string1.pointer,
        i,
        i1,
      ).reference,
    );
  }

  static final _id_asLandscape = _class.instanceMethodId(
    r'asLandscape',
    r'()Landroid/print/PrintAttributes$MediaSize;',
  );

  static final _asLandscape =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$MediaSize asLandscape()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$MediaSize? asLandscape() {
    return _asLandscape(
      reference.pointer,
      _id_asLandscape as jni$_.JMethodIDPtr,
    ).object<PrintAttributes$MediaSize?>(
      const $PrintAttributes$MediaSize$NullableType$(),
    );
  }

  static final _id_asPortrait = _class.instanceMethodId(
    r'asPortrait',
    r'()Landroid/print/PrintAttributes$MediaSize;',
  );

  static final _asPortrait =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$MediaSize asPortrait()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$MediaSize? asPortrait() {
    return _asPortrait(
      reference.pointer,
      _id_asPortrait as jni$_.JMethodIDPtr,
    ).object<PrintAttributes$MediaSize?>(
      const $PrintAttributes$MediaSize$NullableType$(),
    );
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }

  static final _id_getHeightMils = _class.instanceMethodId(
    r'getHeightMils',
    r'()I',
  );

  static final _getHeightMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getHeightMils()`
  int getHeightMils() {
    return _getHeightMils(
      reference.pointer,
      _id_getHeightMils as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getId = _class.instanceMethodId(
    r'getId',
    r'()Ljava/lang/String;',
  );

  static final _getId =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getId() {
    return _getId(
      reference.pointer,
      _id_getId as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getLabel = _class.instanceMethodId(
    r'getLabel',
    r'(Landroid/content/pm/PackageManager;)Ljava/lang/String;',
  );

  static final _getLabel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.lang.String getLabel(android.content.pm.PackageManager packageManager)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getLabel(jni$_.JObject? packageManager) {
    final _$packageManager = packageManager?.reference ?? jni$_.jNullReference;
    return _getLabel(
      reference.pointer,
      _id_getLabel as jni$_.JMethodIDPtr,
      _$packageManager.pointer,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getWidthMils = _class.instanceMethodId(
    r'getWidthMils',
    r'()I',
  );

  static final _getWidthMils =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getWidthMils()`
  int getWidthMils() {
    return _getWidthMils(
      reference.pointer,
      _id_getWidthMils as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_hashCode$1 = _class.instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  int hashCode$1() {
    return _hashCode$1(
      reference.pointer,
      _id_hashCode$1 as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_isPortrait = _class.instanceMethodId(r'isPortrait', r'()Z');

  static final _isPortrait =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isPortrait()`
  bool isPortrait() {
    return _isPortrait(
      reference.pointer,
      _id_isPortrait as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }
}

final class $PrintAttributes$MediaSize$NullableType$
    extends jni$_.JType<PrintAttributes$MediaSize?> {
  @jni$_.internal
  const $PrintAttributes$MediaSize$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$MediaSize;';

  @jni$_.internal
  @core$_.override
  PrintAttributes$MediaSize? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : PrintAttributes$MediaSize.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes$MediaSize?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$MediaSize$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$MediaSize$NullableType$) &&
        other is $PrintAttributes$MediaSize$NullableType$;
  }
}

final class $PrintAttributes$MediaSize$Type$
    extends jni$_.JType<PrintAttributes$MediaSize> {
  @jni$_.internal
  const $PrintAttributes$MediaSize$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$MediaSize;';

  @jni$_.internal
  @core$_.override
  PrintAttributes$MediaSize fromReference(jni$_.JReference reference) =>
      PrintAttributes$MediaSize.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes$MediaSize?> get nullableType =>
      const $PrintAttributes$MediaSize$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$MediaSize$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$MediaSize$Type$) &&
        other is $PrintAttributes$MediaSize$Type$;
  }
}

/// from: `android.print.PrintAttributes$Resolution`
class PrintAttributes$Resolution extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintAttributes$Resolution> $type;

  @jni$_.internal
  PrintAttributes$Resolution.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/print/PrintAttributes$Resolution',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Resolution?> nullableType =
      $PrintAttributes$Resolution$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes$Resolution> type =
      $PrintAttributes$Resolution$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;II)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1, int i, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PrintAttributes$Resolution(
    jni$_.JString? string,
    jni$_.JString? string1,
    int i,
    int i1,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    return PrintAttributes$Resolution.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$string.pointer,
        _$string1.pointer,
        i,
        i1,
      ).reference,
    );
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }

  static final _id_getHorizontalDpi = _class.instanceMethodId(
    r'getHorizontalDpi',
    r'()I',
  );

  static final _getHorizontalDpi =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getHorizontalDpi()`
  int getHorizontalDpi() {
    return _getHorizontalDpi(
      reference.pointer,
      _id_getHorizontalDpi as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getId = _class.instanceMethodId(
    r'getId',
    r'()Ljava/lang/String;',
  );

  static final _getId =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getId() {
    return _getId(
      reference.pointer,
      _id_getId as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getLabel = _class.instanceMethodId(
    r'getLabel',
    r'()Ljava/lang/String;',
  );

  static final _getLabel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getLabel()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getLabel() {
    return _getLabel(
      reference.pointer,
      _id_getLabel as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getVerticalDpi = _class.instanceMethodId(
    r'getVerticalDpi',
    r'()I',
  );

  static final _getVerticalDpi =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getVerticalDpi()`
  int getVerticalDpi() {
    return _getVerticalDpi(
      reference.pointer,
      _id_getVerticalDpi as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_hashCode$1 = _class.instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  int hashCode$1() {
    return _hashCode$1(
      reference.pointer,
      _id_hashCode$1 as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }
}

final class $PrintAttributes$Resolution$NullableType$
    extends jni$_.JType<PrintAttributes$Resolution?> {
  @jni$_.internal
  const $PrintAttributes$Resolution$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Resolution;';

  @jni$_.internal
  @core$_.override
  PrintAttributes$Resolution? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : PrintAttributes$Resolution.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes$Resolution?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$Resolution$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$Resolution$NullableType$) &&
        other is $PrintAttributes$Resolution$NullableType$;
  }
}

final class $PrintAttributes$Resolution$Type$
    extends jni$_.JType<PrintAttributes$Resolution> {
  @jni$_.internal
  const $PrintAttributes$Resolution$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes$Resolution;';

  @jni$_.internal
  @core$_.override
  PrintAttributes$Resolution fromReference(jni$_.JReference reference) =>
      PrintAttributes$Resolution.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes$Resolution?> get nullableType =>
      const $PrintAttributes$Resolution$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$Resolution$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$Resolution$Type$) &&
        other is $PrintAttributes$Resolution$Type$;
  }
}

/// from: `android.print.PrintAttributes`
class PrintAttributes extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PrintAttributes> $type;

  @jni$_.internal
  PrintAttributes.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/print/PrintAttributes');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes?> nullableType =
      $PrintAttributes$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PrintAttributes> type = $PrintAttributes$Type$();

  /// from: `static public final int COLOR_MODE_COLOR`
  static const COLOR_MODE_COLOR = 2;

  /// from: `static public final int COLOR_MODE_MONOCHROME`
  static const COLOR_MODE_MONOCHROME = 1;
  static final _id_CREATOR = _class.staticFieldId(
    r'CREATOR',
    r'Landroid/os/Parcelable$Creator;',
  );

  /// from: `static public final android.os.Parcelable$Creator<android.print.PrintAttributes> CREATOR`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JObject? get CREATOR =>
      _id_CREATOR.get(_class, const jni$_.$JObject$NullableType$());

  /// from: `static public final int DUPLEX_MODE_LONG_EDGE`
  static const DUPLEX_MODE_LONG_EDGE = 2;

  /// from: `static public final int DUPLEX_MODE_NONE`
  static const DUPLEX_MODE_NONE = 1;

  /// from: `static public final int DUPLEX_MODE_SHORT_EDGE`
  static const DUPLEX_MODE_SHORT_EDGE = 4;
  static final _id_describeContents = _class.instanceMethodId(
    r'describeContents',
    r'()I',
  );

  static final _describeContents =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int describeContents()`
  int describeContents() {
    return _describeContents(
      reference.pointer,
      _id_describeContents as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }

  static final _id_getColorMode = _class.instanceMethodId(
    r'getColorMode',
    r'()I',
  );

  static final _getColorMode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getColorMode()`
  int getColorMode() {
    return _getColorMode(
      reference.pointer,
      _id_getColorMode as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getDuplexMode = _class.instanceMethodId(
    r'getDuplexMode',
    r'()I',
  );

  static final _getDuplexMode =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getDuplexMode()`
  int getDuplexMode() {
    return _getDuplexMode(
      reference.pointer,
      _id_getDuplexMode as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_getMediaSize = _class.instanceMethodId(
    r'getMediaSize',
    r'()Landroid/print/PrintAttributes$MediaSize;',
  );

  static final _getMediaSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$MediaSize getMediaSize()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$MediaSize? getMediaSize() {
    return _getMediaSize(
      reference.pointer,
      _id_getMediaSize as jni$_.JMethodIDPtr,
    ).object<PrintAttributes$MediaSize?>(
      const $PrintAttributes$MediaSize$NullableType$(),
    );
  }

  static final _id_getMinMargins = _class.instanceMethodId(
    r'getMinMargins',
    r'()Landroid/print/PrintAttributes$Margins;',
  );

  static final _getMinMargins =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$Margins getMinMargins()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Margins? getMinMargins() {
    return _getMinMargins(
      reference.pointer,
      _id_getMinMargins as jni$_.JMethodIDPtr,
    ).object<PrintAttributes$Margins?>(
      const $PrintAttributes$Margins$NullableType$(),
    );
  }

  static final _id_getResolution = _class.instanceMethodId(
    r'getResolution',
    r'()Landroid/print/PrintAttributes$Resolution;',
  );

  static final _getResolution =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.print.PrintAttributes$Resolution getResolution()`
  /// The returned object must be released after use, by calling the [release] method.
  PrintAttributes$Resolution? getResolution() {
    return _getResolution(
      reference.pointer,
      _id_getResolution as jni$_.JMethodIDPtr,
    ).object<PrintAttributes$Resolution?>(
      const $PrintAttributes$Resolution$NullableType$(),
    );
  }

  static final _id_hashCode$1 = _class.instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  int hashCode$1() {
    return _hashCode$1(
      reference.pointer,
      _id_hashCode$1 as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_writeToParcel = _class.instanceMethodId(
    r'writeToParcel',
    r'(Landroid/os/Parcel;I)V',
  );

  static final _writeToParcel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public void writeToParcel(android.os.Parcel parcel, int i)`
  void writeToParcel(jni$_.JObject? parcel, int i) {
    final _$parcel = parcel?.reference ?? jni$_.jNullReference;
    _writeToParcel(
      reference.pointer,
      _id_writeToParcel as jni$_.JMethodIDPtr,
      _$parcel.pointer,
      i,
    ).check();
  }
}

final class $PrintAttributes$NullableType$
    extends jni$_.JType<PrintAttributes?> {
  @jni$_.internal
  const $PrintAttributes$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes;';

  @jni$_.internal
  @core$_.override
  PrintAttributes? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : PrintAttributes.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$NullableType$) &&
        other is $PrintAttributes$NullableType$;
  }
}

final class $PrintAttributes$Type$ extends jni$_.JType<PrintAttributes> {
  @jni$_.internal
  const $PrintAttributes$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/print/PrintAttributes;';

  @jni$_.internal
  @core$_.override
  PrintAttributes fromReference(jni$_.JReference reference) =>
      PrintAttributes.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PrintAttributes?> get nullableType =>
      const $PrintAttributes$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PrintAttributes$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PrintAttributes$Type$) &&
        other is $PrintAttributes$Type$;
  }
}
