// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by ffigen

// ignore_for_file: unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Generates a PDF from HTML content asynchronously.
/// @param html The HTML string to convert.
/// @param output_path The file path to save the PDF.
/// @param callback The callback to invoke when generation is complete.
@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int32 result)>>)>()
external void generate_pdf(
  ffi.Pointer<ffi.Char> html,
  ffi.Pointer<ffi.Char> output_path,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int32 result)>> callback,
);

/// Generates a PDF from a URL asynchronously.
/// @param url The URL to convert.
/// @param output_path The file path to save the PDF.
/// @param callback The callback to invoke when generation is complete.
@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int32 result)>>)>()
external void generate_pdf_from_url(
  ffi.Pointer<ffi.Char> url,
  ffi.Pointer<ffi.Char> output_path,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int32 result)>> callback,
);
