// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for native_pdf_engine C++ shims
class native_pdf_engine_c_bindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  native_pdf_engine_c_bindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  native_pdf_engine_c_bindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Void> NativePdf_CreateEngine() {
    return _NativePdf_CreateEngine();
  }

  late final _NativePdf_CreateEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'NativePdf_CreateEngine',
      );
  late final _NativePdf_CreateEngine =
      _NativePdf_CreateEnginePtr.asFunction<ffi.Pointer<ffi.Void> Function()>();

  void NativePdf_DestroyEngine(ffi.Pointer<ffi.Void> engine) {
    return _NativePdf_DestroyEngine(engine);
  }

  late final _NativePdf_DestroyEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'NativePdf_DestroyEngine',
      );
  late final _NativePdf_DestroyEngine =
      _NativePdf_DestroyEnginePtr.asFunction<
        void Function(ffi.Pointer<ffi.Void>)
      >();

  void NativePdf_Generate(
    ffi.Pointer<ffi.Void> engine,
    ffi.Pointer<ffi.Char> content,
    bool is_url,
    ffi.Pointer<ffi.Char> output_path,
    PdfCompletionCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _NativePdf_Generate(
      engine,
      content,
      is_url,
      output_path,
      callback,
      user_data,
    );
  }

  late final _NativePdf_GeneratePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Bool,
            ffi.Pointer<ffi.Char>,
            PdfCompletionCallback,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('NativePdf_Generate');
  late final _NativePdf_Generate =
      _NativePdf_GeneratePtr.asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          bool,
          ffi.Pointer<ffi.Char>,
          PdfCompletionCallback,
          ffi.Pointer<ffi.Void>,
        )
      >();
}

typedef PdfCompletionCallbackFunction =
    ffi.Void Function(
      ffi.Bool success,
      ffi.Pointer<ffi.Char> error_message,
      ffi.Pointer<ffi.Uint8> data,
      ffi.Int32 length,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef DartPdfCompletionCallbackFunction =
    void Function(
      bool success,
      ffi.Pointer<ffi.Char> error_message,
      ffi.Pointer<ffi.Uint8> data,
      int length,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef PdfCompletionCallback =
    ffi.Pointer<ffi.NativeFunction<PdfCompletionCallbackFunction>>;
